### ISSUE TITLE
The Index.php page would not render but the index.html

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#10]
Hello Everyone,
I followed the lecture step by step. Anytime I try the server, it always renders the index.html page instead of index.php page like in the lecture. I am attaching the configuration of my server to this message. Every other step run successfully. Can I please get some help?
Anticipated thanks,
Yvaral
![server](https://user-images.githubusercontent.com/42287520/152910094-da24426a-dc4e-4b1b-b282-28ba12d99f3f.JPG)
![html_page](https://user-images.githubusercontent.com/42287520/152910104-d46237da-bfac-4e4c-affa-7132312c15e1.JPG)

**Comment by susanBuck** [comment]
Hi @YvaGithub -

Can you confirm you restarted your server after adding the e15practice subdomain configuration?

You can do that with this command:

```bash
> systemctl restart nginx
```

If you've already done this and it's still not working let me know and we can explore other possible causes.

**Comment by YvaGithub** [comment]
Hi,
Yes I did restart the server and I did it again with no success. I even clear the history on my browser but it is still not working. I kind walked back all the steps.
Thanks,
Yvaral
![server2](https://user-images.githubusercontent.com/42287520/153035156-3c2e7062-1105-4f93-9641-acba581b0642.JPG)

**Comment by gkorodi** [comment]
![Screen Shot 2022-02-08 at 11.58.46 AM](http://static.gitscout.com/c428a8c0a883eeb019c50a27e0ccd3b12c78d0e575a3e12a67452b7b7adc2ca3.png)

Your URL http://e15practice.yvaralljame.me/ shows correctly for me. In case that is what you want to show?!

**Comment by archerdave** [comment]
I'm seeing the same page as @gkorodi.  This makes me wonder @YvaGithub if your browser has cached the original page that you loaded, and not yet noticed that the page has changed.  I would suggest any of the following:
- Clear your browser's cache, not just the history.
- Try the site in an incognito window
- Try the site in a different web browser altogether
- Try the site from a different device (a different computer, a mobile device, etc)

**Comment by YvaGithub** [comment]
Thank you. My bad! I never added the subdomain (e15practice.) to the URL. It is working now. Again thank you

**Comment by xul889** [comment]
I have the same problem and it is solved now. Thank you!
