### ISSUE TITLE
Linefeed misbehavior in README

### ISSUE THREAD

**Issue by archerdave** [susanBuck/e15-spring22#11]
In looking at my README file in GitHub, I noticed that the text `By: David Harvill` which I added to a new line at the end of the file, is actually showing up on the same line as the line above when it displays in Git Hub.

Here are the contents of README.md:
```
# e15
Coursework for CSCI E-15, Spring 2022
By: David Harvill
```

And here is what is showing up in the GitHub repository.
<img width="536" alt="Screen Shot 2022-02-08 at 4 21 48 PM" src="https://user-images.githubusercontent.com/2293085/153078182-4ec33745-31b4-42f8-b2c8-afc44a4adccd.png">

If I add an empty line in between in the README.md, like this...
```
# e15
Coursework for CSCI E-15, Spring 2022

By: David Harvill
```

... then the new lines all show up properly, like this:
<img width="699" alt="Screen Shot 2022-02-08 at 4 32 37 PM" src="https://user-images.githubusercontent.com/2293085/153079225-bbe77d7c-bc34-49f8-93d3-394c51e4d048.png">

I did verify that I set git's handling of CRLF as described in the notes:
```
root@hes:~/.ssh# git config --global -l
user.name=David Harvill
user.email=dharvill@gmail.com
color.ui=true
core.filemode=false
core.autocrlf=input
```

Any ideas what might be going on?

**Comment by archerdave** [comment]
And looking back at the class video part 5, at 7:14, it looks like Susan Buck's README file is displaying the same way.  Maybe markdown needs an empty line to show a newline?

**Comment by gkorodi** [comment]
I think you are picking up on Markdown's "features" that are not so obvious. A newline "CR" or "CRLF" is NOT a `<br />` in Markdown :(

This might help: https://daringfireball.net/projects/markdown/syntax#p

**Comment by archerdave** [comment]
Okay, so typing this out helped me think through it a bit more, and I found what I needed in the markdown syntax guide.

https://www.markdownguide.org/basic-syntax/#line-breaks
