### ISSUE TITLE
Help With My vowels Count Function

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#14]
Hello everyone,
I got my vowel count function to work but only when I hardcoded a string into it. I am attaching a snippet of code for some suggestions please.
Anticipated thanks,
Yvaral

![snippet](https://user-images.githubusercontent.com/42287520/153983585-47e7ff73-4660-4fb4-8361-531737491167.JPG)
![snippet2](https://user-images.githubusercontent.com/42287520/153983628-08ad7a9e-ea5b-4d83-a9ad-66a3aa358175.JPG)
![snippet3](https://user-images.githubusercontent.com/42287520/153983643-60f97f89-de22-4be8-bad8-dd171fdd8db1.JPG)

**Comment by susanBuck** [comment]
Hi @YvaGithub -

> I got my vowel count function to work but only when I hardcoded a string into it

How exactly is it failing when you try to pass in the string from the form?

In your code, I see you do this in process.php on line 6:

```php
$vowelCount = NumberofVowels($inputString);
```

That should work - you just need to output the resulting _$vowelCount_ variable as part of your results in the view file, e.g. something like this:

```php
There are <?php echo $vowelCount; ?> vowel(s) in this word.
```

**Comment by YvaGithub** [comment]
Thank you very much it works now.
