### ISSUE TITLE
PHP code is not being formatted in VSC

### ISSUE THREAD

**Issue by archerdave** [susanBuck/e15-spring22#16]
This is a minor issue, but an annoyance.  Visual Studio Code (VSC) is not actually formatting my PHP code.

- This wrong behavior exists on both local and remote machines
- The extension "php cs fixer" is installed both locally and remotely.
![Screen Shot 2022-02-15 at 8 23 21 PM](https://user-images.githubusercontent.com/2293085/154178514-41ec746f-6926-4728-be0f-9f4658647a01.png)
- In the screenshot below, you can see that I have no space between ```if``` and ```(issset``` and that the next line ```$results = ...``` has no indentation.
![Screen Shot 2022-02-15 at 8 26 49 PM](https://user-images.githubusercontent.com/2293085/154178852-00f311d4-2d8d-4318-a588-42c415309688.png)
- Also note that the file has been saved; there is no large dot next to the filename at the top.  Had it not been saved, it would look like this:
![Screen Shot 2022-02-15 at 8 31 28 PM](https://user-images.githubusercontent.com/2293085/154179150-cb5c9d5d-9d9c-458c-916c-5af787b84146.png)
- As I have "Formate On Save" enabled, this should not be possible.
![Screen Shot 2022-02-15 at 8 29 24 PM](https://user-images.githubusercontent.com/2293085/154178988-3d226108-4ba5-4e27-a4a6-7e2d50e711f0.png)
- VSC is formatting other code, such as HTML code in HTML files, as I save them.

Any thoughts?

**Comment by susanBuck** [comment]
@archerdave Looks like you've got everything set up correctly. Do you mind if I log into your server to take a look?

**Comment by archerdave** [comment]
@susanBuck Go right ahead.

**Comment by susanBuck** [comment]
Cool, taking a look now, will report back shortly.

**Comment by susanBuck** [comment]
When I first logged in, I saw the issue you were describing - it wouldn't format. 

I spent a couple minutes double checking the settings, trying some files, and then it just started working without me actually changing anything.

I did notice that when it wasn't working that there was a message in the status bar about intelephense indexing the project. It's possible the formatter couldn't work until that was complete.

Can you try it again on your end to see if it's resolved or if you're still seeing the same issue?

**Comment by archerdave** [comment]
Issue is still present.  Working from your comment, I have further noticed the following:
![Screen Shot 2022-02-15 at 9 51 22 PM](https://user-images.githubusercontent.com/2293085/154187162-0084c83c-659b-410d-93dc-9d06ddd22b68.png)

![Screen Shot 2022-02-15 at 9 51 42 PM](https://user-images.githubusercontent.com/2293085/154187178-d7b1bec3-ed14-42cc-8810-24a375797981.png)

**Comment by susanBuck** [comment]
Ah, ok - interesting.

In my local settings config file, I have the default formatter for PHP set to junstyle.php-cs-fixer:

```json
 "[php]": {
        "editor.defaultFormatter": "junstyle.php-cs-fixer"
    },
```

That would explain why it worked for me but not you.

Go ahead and choose php cs fixer as your default formatter and report back on whether that resolves the issue.

If it does, I'm trying to figure out why this issue hasn't been faced/reported by students in past semesters. 🤔

**Comment by archerdave** [comment]
Yep, that did resolve the issue.

My first thoughts wonder if it is related to

- the order that I installed the extensions
  - which I didn't keep track of
- Intelephense getting an update
