### ISSUE TITLE
Laravel App is getting error - 502 bad gateway

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#18]
Hi,

 I am getting the 502 bad gateway error when I am trying to access 'bookmark' app. After some research on digital ocean, 
https://www.digitalocean.com/community/questions/502-gateway-error-on-nginx-running-a-laravel-app

I am not sure if we need to increase the memory or something? My other projects are working fine. Any other suggestions please....

Thanks

**Comment by susanBuck** [comment]
Hi @mgarimelHES -

+ What is the URL? 
+ Can you share the contents of your hes sites config file (`/etc/nginx/sites-available/hes`)? 
+ Can you share the output of the command `nginx -t`, confirming there are no errors in your configs?

**Comment by mgarimelHES** [comment]
Hi @susanBuck ,

 Thanks, the issue is due to the old version of php7.x-fpm, after upgrading it to php8.0-fpm and restart the issue is resolved.

Regards,

**Comment by susanBuck** [comment]
@mgarimelHES Glad you were able to sort it out. : )
