### ISSUE TITLE
Week1 - Assignment1 access issue

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#2]
Hi **Susan**,

 I am not able to access the week1 assignment, please have a look at this *screenshot* -

![image](https://user-images.githubusercontent.com/64241541/151709943-d9e8280b-3dd6-404a-866b-024d40ca1577.png)

BTW, I am trying to access it from the Canvas!

Thanks for your help,

**Comment by archerdave** [comment]
Have you tried logging out of Canvas, then logging back in?

**Comment by mgarimelHES** [comment]
I have tried a different browser too, same issue.



Regards,

Murthy Garimella

HES - ALM

**Comment by susanBuck** [comment]
@mgarimelHES  - I'm able to recreate the screen you're seeing if I try and access the assignment but I'm not logged in to Canvas. 

Can you confirm you're logged in?

Note: 
When you're not logged in, the icon on the top of the Canvas menu on the left says "Login"
When you are logged in, it says "Account"

**Comment by mgarimelHES** [comment]
Thanks, it is working now. I have cleared the browser cache and closed all
the tabs and restarted the session.



Regards,

Murthy Garimella

HES - ALM

**Comment by mgarimelHES** [comment]
It is resolved!  I am closing the issue now.

Thanks a lot!
