### ISSUE TITLE
P2 Potential Idea - Text Encryption

### ISSUE THREAD

**Issue by dauger27** [susanBuck/e15-spring22#22]
My first idea was similar to the [Pig Latin](https://s3.amazonaws.com/dwa15.com/wireframe-pig-latin-translator@2x.png) example, a basic text "encryption" application.

# Text Encryption
## Message
This would be a text box which would collect the user's text to modify. I would explicitly mention that non-alpha characters are left unencrypted to reduce complexity at this time.

## Encryption Type
This section would be radio buttons:
- [Caesar Cipher](https://en.wikipedia.org/wiki/Caesar_cipher)
- Scrambled (mixing letters up except for first and last).
- *Both (doing one followed by the other in some order) - not certain yet if I would this*

The types above would have subset information required.

### Caesar Cipher
- A dropdown to determine left/right encryption.
- A text field to determine the numeric shift (text field over dropdown to allow for data validation).

### Scrambled
- A checkbox to scramble 2/3-letter words (which by default wouldn't be scrambled).

### Both
- A dropdown to determine the order of operation of the other types.

Does this seem doable for Project 2?

**Comment by susanBuck** [comment]
@dauger27 - Sounds like a great concept for Project 2, and certainly doable. I like your clear/organized plan.
