### ISSUE TITLE
I am a bit confused on the Week 5, Question 2 requirement

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#26]
Hello Everyone,
For the second question, I am a bit confused where it says: "initialize a new p2
 Laravel application within the e15 directory, making it accessible via http://e15p1.yourdomain.com. The "p1" in the url throws me off a bit. Is p2 instead or is it p2 inside of p1?

Anticipated thanks,
Yvaral

**Comment by pllealfunes** [comment]
You have to create the p2 project in the e15 directory. Take a look at the notes on how to create a new Laravel project to do this. The url will be the same as above but change p1 to p2.

**Comment by YvaGithub** [comment]
I do know how to create it. My confusion was the way I read the requirement
for the url. I did create it the right way, I just wanted to make sure I
was doing it correctly.
Thanks

**Comment by susanBuck** [comment]
This was a typo on my part. p1 should be p2. I will correct it.

**Comment by YvaGithub** [comment]
Thank you!
