### ISSUE TITLE
FYI - New server extensions needed for Laravel

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring22#27]
Hi everyone,

Two new PHP extensions were recently added as Laravel requirements, and if you don't have them you'll get errors from Composer next time you go to install/create a new Laravel project (e.g. when you initialize P3). You'll also get the error if you run `composer update` in your existing Bookmark or p1 applications.

To address this, you need to add the extensions on your server. To do this, first run `php --version` to see if you're running PHP 8.0 or 8.1 from command line.

Then, run the following command, swapping in `8.x` with either `8.1` or `8.0` depending on the previous results.

```bash
> sudo apt-get install php8.x-curl php8.x-xml
```

Hat tip to @mgarimelHES for discovering this; ref: #25.

**Comment by archerdave** [comment]
@susanBuck running these commands, I received an error after the second one:

```
~# sudo apt-get install php8.1-curl php-8.1xml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php-8.1xml
E: Couldn't find any package by glob 'php-8.1xml'
E: Couldn't find any package by regex 'php-8.1xml'
```

I moved the hyphen in the name of the XML package to match the location in the name of the CURL package, `sudo apt-get install php8.1-curl php8.1-xml` and it seems to have worked properly.

**Comment by susanBuck** [comment]
@archerdave - Thanks for that catch - fixed my original post. 👍
