### ISSUE TITLE
FYI - Watch out your charges on Digital Ocean Server

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#28]
Friends,

 Due to a bug as per Digital Ocean support team, suddenly my Droplet had upgraded with more memory and CPU which has resulted in a billing around $40.00. 

At present I am still working with them to get any refund or downsize my Droplet to its original config. Apparently once it is upgraded with more memory and cpu, it is not possible to bring it now. One option is create another droplet and redo all your work till week5.

Please watch out your billing / invoice.

Thanks

**Comment by susanBuck** [comment]
Hi @mgarimelHES -  How odd they would accidentally upgrade you. Sorry to hear that happened. 

Doing a server migration shouldn't be too big of a hassle. All your code should be backed up on Github, so you'd be able to just clone your work to the new server.

If you'd like I can configure a new server for you. I could make a screencast of it and share it with the class so everyone could see the process. 

If you want to do this, you'd just have to complete the steps to create a new [LEMP droplet](https://hesweb.dev/e15/notes/infrastructure/servers-setup), then follow the instructions for [granting instructor access](https://hesweb.dev/e15/notes/infrastructure/servers-config#instructor-server-access).

Once you do that, just tell me your new server's IP address and I can take it from there.

**Comment by mgarimelHES** [comment]
Hi Susan,

 Thanks for your help, I will work on it this weekend and let you know how
it goes.

Appreciate your help as always!

Regards,

Murthy Garimella

HES - ALM

**Comment by YvaGithub** [comment]
I have the same complaint. They charged $44. last month. And I notice the more charge building up for this month. And it seems there is no means to contact them. I forget if we were supposed to get charged anyway.

**Comment by susanBuck** [comment]
@YvaGithub I'm sorry to hear that. This is very odd. 

Could either/both of you share a screenshot of your February invoice? You can omit the address/personal details, just show the droplet totals (example below)

Here's how to find your invoice:
+ Log into DO
+ Click Billing from the menu on the left
+ Scroll down to Billing history
+ Next to the "Invoice for February 2022", click PDF to download

As an example, here's my invoice:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/237711/156950118-83456727-d67d-4660-993b-402684d8136c.png">

**Comment by YvaGithub** [comment]
![invoice](https://user-images.githubusercontent.com/42287520/156953038-f5d24aea-0efd-4e25-8d60-77e7bc71aac2.JPG)
![pic1](https://user-images.githubusercontent.com/42287520/156953056-7ddcb186-31da-43d9-ab95-76ec751b7a90.JPG)
![pic2](https://user-images.githubusercontent.com/42287520/156953070-0e4c2a8d-c588-4734-824e-5855a92495a5.JPG)
![pic3](https://user-images.githubusercontent.com/42287520/156953088-e379b228-84a5-4d18-9b48-676bf0440c3b.JPG)

**Comment by YvaGithub** [comment]
Please let me know if anything else is needed

**Comment by susanBuck** [comment]
Thanks @YvaGithub -

It looks like you have the 8gb 4 CPU plan ($40/mo) which is the default plan selected when creating a new Droplet. You have to choose the cheaper $5/mo plan.

Here's a reference shot [from the notes showing the plan we should be using](https://hesweb.dev/e15/notes/infrastructure/servers-setup):

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/237711/156953844-93ac7069-560c-4c78-8786-c6d43a0475e3.png">

As @mgarimelHES noted - there's no way to downgrade a Droplet, you can only start a new one. Please let me know if I can assist you with that.

**Comment by mgarimelHES** [comment]
The is is due to some 'bug' on DigitalServr site, the droplet will be 'upgraded' from 1 GB basic server to 8 GB server which is causing this sudden increase in the price. We can not go back to the original size, only option is create a new droplet with basic and move your code to the new droplet and delete this high cost droplet. I have followed this over this weekend.

HTH

**Comment by YvaGithub** [comment]
Thank you

**Comment by susanBuck** [comment]
Thanks for the information, @mgarimelHES. Can you confirm if the unrequested upgrade happened right from the start, e.g. you created the Droplet specifying the $5/mo plan but when it went through it went through as the $40/mo plan?

Or did it initiate as a $5/mo plan and later upgrade to $40/mo?

Can you also share DigitalOcean's response/explanation of the problem with me, either here or via email if you prefer?

Appreciate your help in understanding this problem!

**Comment by mgarimelHES** [comment]
Response from the support - 

```
I understand your concern with the reported charges.

Looking at the logs I see that the $40 Droplet was spun on the 31st of January 2022 in addition to the $5 Droplet and since then it has incurred charges.

We confirm that the $40 Droplet wasn’t created by us or was there a bug that resulted in the said charges.

You can verify the security history section to verify the Droplet creation IP.

Looks like the Droplet in question was created unintentionally
```

I am sure that I did not create this droplet with more capacity.

**Comment by susanBuck** [comment]
Just an update for anyone watching this thread: I've confirmed with both @YvaGithub and @mgarimelHES that they were able to set up a new $5/mo server and get everything migrated.

I'm going to leave this thread open for a little bit more, just so it's on the radar of other students and there aren't any other unanticipated charges.

I'm not 100% sure why/how this happened. From DO's reply, it sounds like they don't think they're culpable. Regardless, I'll definitely keep an eye out for this in future semesters and remind students to keep an eye on their charges.
