### ISSUE TITLE
Week6 - Assignment Question 2 - Clarification

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#29]
Hi **Susan**,

 In Week-6 assignment, question 2 mentions about the following - 
*Setting up a child template that extends this main template and displays your form. Don't worry yet about submitting/processing this form - we'll cover that next week*

 Q - Do we need to create the *form* since the topic about forms will be covered in the next week?

Thanks

**Comment by susanBuck** [comment]
Hi @mgarimelHES - You can create the form this week, deciding on what inputs you'll need, setting up the labels, etc. 

Next week we’ll be talking about _processing_ the form, but we don't have to wait for that to create/design the form.

**Comment by mgarimelHES** [comment]
Thanks, it is helpful.
