### ISSUE TITLE
Error Updating Composer

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#30]
Hi Everyone,
After I run the   two lines of code which seems to be working, I run composer update. I have gotten the attached error. Any idea what I should to to debug the error.
Anticipated thanks,
Yvaral
![error_updating](https://user-images.githubusercontent.com/42287520/156906273-42aab8d4-2831-4afe-b83b-2d8f1b4a55f8.JPG)

**Comment by susanBuck** [comment]
HI @YvaGithub - You're running it in the e15 directory - try moving into one of your laravel projects (either p2 or bookmark) and run `composer update` there.

**Comment by YvaGithub** [comment]
Thank you, it works when I run in the bookmark project.
