### ISSUE TITLE
What changes when breeze/inertia/vue is used?

### ISSUE THREAD

**Issue by patrickgarsow-harvard** [susanBuck/e15-spring22#31]
So I have been planning my project and working on things. One of the things I was interested in was the authentication piece which Laravel strongly recommends Inertia with Breeze or Jetstream with the built in auth mechanism. I tried just installing the package and it has totally changed my view files and everything doesn't seem to be done from blade files but rather under resources/js/pages/ in .vue files. How can simply implementing another feature of Laravel literally change the core of the view system this much?

**Comment by susanBuck** [comment]
If you want to do API authentication without all the front end scaffolding, you want [Laravel Sanctum](https://laravel.com/docs/9.x/sanctum).

> [Laravel Sanctum](https://github.com/laravel/sanctum) provides a **featherweight authentication system for SPAs (single page applications)**, mobile applications, and simple, token based APIs.

Vs.:

> [Laravel Breeze](https://github.com/laravel/breeze) is a minimal, simple implementation of all of Laravel's [authentication features](https://laravel.com/docs/9.x/authentication), including login, registration, password reset, email verification, and password confirmation. Laravel Breeze's **default view layer** is made up of simple [Blade templates](https://laravel.com/docs/9.x/blade) styled with [Tailwind CSS](https://tailwindcss.com/). Breeze provides a wonderful starting point for **beginning a fresh Laravel application** [...]

The key part of the latter description is it's intended for fresh Laravel applications, which is why/how it can change so much around.

**Comment by patrickgarsow-harvard** [comment]
I was unaware of Sanctum so I will investigate that. Thank you.

I guess my concern on Breeze with Inertia and Vue is that it changes the core structure which is not something we have been taught and I am having difficulty following so I think I just need to step back from that or watch some serious amount of tutorials to understand it more.

**Comment by susanBuck** [comment]
np! There are several auth-related packages (Breeze, Sanctum, Fortify) Laravel provides so sometimes it can be hard to decipher which one you actually need. Someone should make a chart/infographic. : )
