### ISSUE TITLE
SCSS and Laravel?

### ISSUE THREAD

**Issue by luannebe** [susanBuck/e15-spring22#32]
I don't plan to use any complicated CSS for P2 -- since my head is swimming with the essential Laravel concepts -- but I am curious how SCSS and how its transpilation/minification could co-exist with Laravel. Does anyone have any thoughts about this?

**Comment by susanBuck** [comment]
Hi @luannebe - 

Laravel has a tool called Mix that can assist with transpilation/minificiation: https://laravel.com/docs/9.x/mix#main-content

It simplifies the process of working with Webpack, and has support for SCSS. 

If you dig into it and have any questions, let me know. :)

**Comment by luannebe** [comment]
Thank you!!! I will give it a try.

**Comment by luannebe** [comment]
Hi, I installed Mix and Tailwind CSS ... so far so good. Thank you, @susanBuck  !

**Comment by susanBuck** [comment]
@luannebe np!
