### ISSUE TITLE
Do all form inputs have to have server side validation in p2?

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e15-spring22#34]
Hi Susan,

I was wondering if all form inputs in p2 need to have server side validation. My form includes a checkbox that asks the user if they would also like to get an inspirational quote along with the hobbies recommended to them. Since this is optional should it still have validation? Or should I only include inputs that are required in order to fulfill the validation requirement?

**Comment by susanBuck** [comment]
It's okay to omit validation on things like checkboxes and other optional fields that can be omitted. 👍

**Comment by pllealfunes** [comment]
Great thank you!
