### ISSUE TITLE
Project2 - Undefined variable Issue

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#36]
I am following the design-c and using the Bookmark sample, trying to pass a variable and getting the 'undefined variable' as shown below -

![image](https://user-images.githubusercontent.com/64241541/158222115-39407297-3756-46a9-b9e0-969160b54284.png)

I have following the following steps -

1. Created a route in the 'web.php' -

 
![image](https://user-images.githubusercontent.com/64241541/158222430-8700358b-6cac-48f6-a0d3-76f7339d431d.png)

2.  In the view, the 'Get' method is invoking the method -

![image](https://user-images.githubusercontent.com/64241541/158222746-eed81eb0-e38c-4976-a373-bbea4467cea8.png)

3. In the controller, action has been defined and hard coded the value for the 'variable ' as follows -

![image](https://user-images.githubusercontent.com/64241541/158223082-de85b66d-cc96-49e2-a5d0-9c7fa7fc5736.png)

4.  In the view , tried to dump the value after the form -

![image](https://user-images.githubusercontent.com/64241541/158223408-0d623873-a7e0-401d-8251-f000b22d3006.png)

5. But in the view page, getting the error instead of dumping the variable value -

![image](https://user-images.githubusercontent.com/64241541/158223625-d188d47a-a4e5-4fa0-b262-79b2d179fd9c.png)

Any pointers will be great!

Thanks

**Comment by pllealfunes** [comment]
Hi @mgarimelHES, 

You try dumping the variable in the controller. What if you get rid of the dump in the view and only keep the the one in the controller?

**Comment by mgarimelHES** [comment]
Hi @pllealfunes,

 Thanks,  I am trying to dump the variable in the form (step4) as shown in the class this week.  I want to debug if the value has been passed from the controller to the view

Thanks

**Comment by susanBuck** [comment]
Hi @mgarimelHES - 

After doing a redirect and "flashing" data to the session, you need to extract the data from the session using the session() helper. Then the extracted data can be passed to the view. It looks like you're missing these last two steps.

**Comment by susanBuck** [comment]
For an example see the PageController in Bookmark:

https://github.com/susanBuck/e15/blob/3d09d6798f11ba2730c7822643b1865785653a8c/bookmark/app/Http/Controllers/PageController.php#L19

**Comment by mgarimelHES** [comment]
Susan,

 I have done pretty similar, but it is not working for me, getting the variable not defined issue. I have tried to update the 'Bookmark' using a new variable called 'searchTerms2', same issue. I am struck here more than 2 days, not sure about the issue.

Thanks

**Comment by mgarimelHES** [comment]
ok, it is resolved, I have modified the 'create' and 'store' actions.

Thanks
