### ISSUE TITLE
Cannot browse my p2 folder

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#38]
Hello everyone,
I am having a hard time browsing to my p2 folder in which I have one index.php file. Any time I tried, it says : "file not found". I tried to run the codes on the screenshot I have gotten some errors as result. Any hint will help.
Thank you,
Yvaral
![p2](https://user-images.githubusercontent.com/42287520/158500051-59e27642-3de8-4740-b1a4-750dcff888bf.JPG)

**Comment by susanBuck** [comment]
Hi @YvaGithub -

As of this writing, it looks like your p2 directory has a Laravel application installed (as expected), and that application is loading correctly via the URL http://e15p2.yvaralljame.me.

Please let me know if this isn't what you're expecting/if I'm missing something.

**Comment by YvaGithub** [comment]
I solved the issue early this morning. Thank you

**Comment by YvaGithub** [comment]
Yes, that is correct. I was able to fix the issue easily today.
Thank you,
Yvaral
