### ISSUE TITLE
Week 8 -  Laravel Database connection driver issue

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#43]
Hi,

 I am not sure if anyone is facing this issue, I am following the lecture notes (part-5) for database set up and ran into the issue in 'practice-3'

1. Changes to env 

![image](https://user-images.githubusercontent.com/64241541/159800047-0a2c26ce-3fd8-4d1f-864f-fc7ae409d9c4.png)

2. Changes to database and user 'hes' is able to connect from CLI

![image](https://user-images.githubusercontent.com/64241541/159800128-b7c11752-8564-47c9-81ee-f93831b6b921.png)

3. Changes to PracticeController.php are done

![image](https://user-images.githubusercontent.com/64241541/159799969-2a9c8ff7-8801-44e8-a42d-36a930a91027.png)

4. It is failing with the following error -

![image](https://user-images.githubusercontent.com/64241541/159800243-a7286818-c664-4836-884e-64e122e5a88e.png)

**Comment by susanBuck** [comment]
@mgarimelHES - 

Try running the following command, swapping `8.x` with whatever version major/minor version you see when you run `php --version`:

```bash
> sudo apt-get install php8.x-mysql
```

**Comment by mgarimelHES** [comment]
I am getting the following error after running the above command -

![image](https://user-images.githubusercontent.com/64241541/160012352-ade87794-c7e9-461e-a837-32a10459b069.png)

**Comment by susanBuck** [comment]
Hi @mgarimelHES - You have to swap `8.x` with whatever major/minor version you see when you run `php --version`.

For example, if you see something like version 8.1.3 when you run `php --version`, the command would be:

```bash
> sudo apt-get install php8.1-mysql
```

If it's some version of 8.0.* the command would look like this:

```bash
> sudo apt-get install php8.0-mysql
```

**Comment by mgarimelHES** [comment]
No luck -

![image](https://user-images.githubusercontent.com/64241541/160044625-3855e4e4-4039-4a78-9939-41e79488a13a.png)

**Comment by susanBuck** [comment]
Please run just the following (8.0 vs 8.0.16):

```bash
> sudo apt-get install php8.0-mysql
```

**Comment by mgarimelHES** [comment]
Thanks, this `sudo apt-get install php8.0-mysql` statement resolved my issue.

Appreciate your help

**Comment by susanBuck** [comment]
I'm going to re-open this issue just in case other students face this problem this week. Thanks for posting, @mgarimelHES.
