### ISSUE TITLE
Prod environment - How to use HTTPS

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#48]
Hello **Susan**,

 I am wondering if you are going to cover in following weeks about how to set up HTTPS for a production environment? 

Thanks,

**Comment by susanBuck** [comment]
I have notes on that I can share this week. Will reply again when they're ready.

**Comment by susanBuck** [comment]
Here you go: https://hesweb.dev/e15/notes/infrastructure/https
