### ISSUE TITLE
Week8 - Housekeeping lesson follow-up Q

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#49]
Hi **Susan**,

 In my practice for 'Reviews' table for  the week8, I have done the following - (please note the field 'book_id' ) -

  Schema::create('reviews', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string('book_id');
            $table->string('first_name');
            $table->string('last_name');
            $table->tinyInteger('rating');
            $table->boolean('recommended');
            $table->text('content');
        });

Q - Is it ok if I assume 'book_id' as an alpha-numeric value instead of an integer?

Thanks

Murthy

**Comment by susanBuck** [comment]
Hi @mgarimelHES -

The data type for _book_id_ should be the same data type used for _id_ in the _books_ table, since that's the corresponding value it will hold.

So let's take a closer look at the id field in the books table...

It's created using the [id](https://laravel.com/docs/9.x/migrations#column-method-id) method, which we're told is just an alias for [bigIncrements](https://laravel.com/docs/9.x/migrations#column-method-bigIncrements).

From the docs we see that _bigIncrements_ creates a field of the data type BIGINT.

So to match this for our _book_id_ field in the reviews table, we should use the method [bigInteger](https://laravel.com/docs/9.x/migrations#column-method-bigInteger).

I just corrected my example/solution to reflect this, as I mistakenly used _integer_ instead of _bigInteger_.

**Comment by patrickgarsow-harvard** [comment]
@mgarimelHES The work you are completing with relational fields is fascinating.

Like Susan stated the field type of the foreign table reference needs to match that of the primary field being referred to and as specific as if integer then it can't be of a larger or smaller size referenced (ie: tinyInt or bigInt).

Also, I have found it useful to make sure in my migration that the field I am referencing from another table has a foreign key reference that I use the foreign()->references()->on().

I have noted that if we  follow conventions it makes things easier as you don't need to explicitly reference all of the details with our relationships, meaning that if you have setup your primary keys to reference a standard "id" field then the foreign reference is assumed to be <model>_id.  

```PHP
$table->integer('contact_id')->unsigned();
$table->foreign('contact_id')->references('id')->on('contacts');
```

**Comment by YvaGithub** [comment]
#

> Hi **Susan**,
> 
> In my practice for 'Reviews' table for the week8, I have done the following - (please note the field 'book_id' ) -
> 
> Schema::create('reviews', function (Blueprint $table) { $table->id(); $table->timestamps(); $table->string('book_id'); $table->string('first_name'); $table->string('last_name'); $table->tinyInteger('rating'); $table->boolean('recommended'); $table->text('content'); });
> 
> Q - Is it ok if I assume 'book_id' as an alpha-numeric value instead of an integer?
> 
> Thanks
> 
> Murthy

This will help me too.
Thanks

**Comment by mgarimelHES** [comment]
> @mgarimelHES The work you are completing with relational fields is fascinating.
> 
> Like Susan stated the field type of the foreign table reference needs to match that of the primary field being referred to and as specific as if integer then it can't be of a larger or smaller size referenced (ie: tinyInt or bigInt).
> 
> Also, I have found it useful to make sure in my migration that the field I am referencing from another table has a foreign key reference that I use the foreign()->references()->on().
> 
> I have noted that if we follow conventions it makes things easier as you don't need to explicitly reference all of the details with our relationships, meaning that if you have setup your primary keys to reference a standard "id" field then the foreign reference is assumed to be _id.
> 
> ```
> $table->integer('contact_id')->unsigned();
> $table->foreign('contact_id')->references('id')->on('contacts');
> ```

Hi @YvaGithub - Thanks for your reply, I think I may have to wait for the 'Relationships' lesson . appreciate your help.
