### ISSUE TITLE
Authentication Setup issue - ext-dom missing

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#53]
Hello **Susan**,

 I am getting the following error while doing the step * composer require laravel/fortify*  -

![image](https://user-images.githubusercontent.com/64241541/163652781-c5a2203b-849d-4b8e-89c6-bac46d246aad.png)

Any suggestions please?

**Comment by patrickgarsow-harvard** [comment]
@mgarimelHES can you check to see if you installed/upgraded to php8?

According to the message you need to run `composer install php-xml` on your server to get the dom extensions for phpunit 

If on php 8 you will want to change that to `composer install php8.0-xml`

**Comment by mgarimelHES** [comment]
Hi @patrickgarsow-harvard ,

 Thanks for your help, I have tried it, but no luck.

Thanks

**Comment by gkorodi** [comment]
Maybe this will help?

It looks like you might need the `ext-dom` extension, which you can add like this

`composer require ext-dom`

and after that, I had no problem adding `fortify` to my composer.json with

`composer require laravel/fortify`

My versions are 

```sh
hes-digitalocean:/var/www/e15/bookmark$ php --version
PHP 8.0.16 (cli) (built: Feb 21 2022 14:42:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies
hes-digitalocean:/var/www/e15/bookmark$ **composer --version**
Composer version 2.2.6 2022-02-04 17:00:38

```

**Comment by susanBuck** [comment]
@mgarimelHES - To cover all your bases on extensions, run the following:

```bash
> sudo apt-get install php8.0-mbstring php8.0-xml php8.0-dom php8.0-curl php8.0-mysql zip unzip
```

Ref: https://hesweb.dev/e15/notes/php/composer#composer-pre-install-extensions

**Comment by mgarimelHES** [comment]
I have followed all the suggestions, unfortunately no luck - same issue!

Thanks @gkorodi & @susanBuck

**Comment by mgarimelHES** [comment]
ok,  it is installed after running the statement - 'sudo apt install php-xml'   
ref - https://www.codegrepper.com/code-examples/php/-+tijsverkoyen%2Fcss-to-inline-styles+2.2.3+requires+ext-dom+%2A+-%3E+the+requested+PHP+extension+dom+is+missing+from+your+system.
