### ISSUE TITLE
migrations won't run - could not find driver

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#55]
Hi,

 This is week is not good for me, running into various issues - Now I am facing the following while following Part-2 lecture notes - (7.15 into recording) for authentication set up=

![image](https://user-images.githubusercontent.com/64241541/163689799-3376c7ee-93ba-42f7-951a-0408853e9422.png)

I have checked my '.env' file and it is looking good and I am able to perform **mysql** from the development server, I have  performed the artisan commands to perform 'clear cache, view:clear, route:clear' successfully.

Any pointers please....

**Comment by susanBuck** [comment]
Hmm, odd "could not find driver" is the same error you faced in Week 8 : https://github.com/susanBuck/e15-spring22/issues/43

I'm going to log into your server and take a look.

**Comment by susanBuck** [comment]
I was unable to log into your server - is 206.189.177.252 the correct IP? (That's what I got when I pinged your hesweb.me domain you've used for projects).

Can you [confirm these steps were follow to grant instructor access](https://hesweb.dev/e15/notes/infrastructure/servers-config#instructor-server-access)?

**Comment by mgarimelHES** [comment]
Hi **Susan**,  

Thanks, I have added you following the steps, hope you can access the sever now.

Regards,

**Comment by susanBuck** [comment]
Excellent, I was able to log in. Will reply again shortly after I take a look.

**Comment by susanBuck** [comment]
Ok, I was able to run your migrations. Here's what I did...

First, I ran `php --version` to determine which version of PHP via command line your system is using.

```
root@hes:/var/www/e15# php --version
PHP 8.1.4 (cli) (built: Apr  4 2022 13:30:17) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies
```

From this, I saw you were running php 8.1 so I ran the following command to make sure your system has all the necessary extensions:

```php
sudo apt-get install php8.1-mbstring php8.1-xml php8.1-dom php8.1-curl zip unzip php8.1-mysql
```

Then I was able to run your migrations:

```bash
root@hes:/var/www/e15/bookmark# php artisan migrate:fresh --seed
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (180.47ms)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (128.03ms)
Migrating: 2014_10_12_200000_add_two_factor_columns_to_users_table
Migrated:  2014_10_12_200000_add_two_factor_columns_to_users_table (170.09ms)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (142.63ms)
Migrating: 2019_12_14_000001_create_personal_access_tokens_table
Migrated:  2019_12_14_000001_create_personal_access_tokens_table (202.76ms)
Migrating: 2022_03_26_045539_create_books_table
Migrated:  2022_03_26_045539_create_books_table (56.40ms)
Migrating: 2022_03_26_171241_create_reviews_table
Migrated:  2022_03_26_171241_create_reviews_table (83.88ms)
Seeding: Database\Seeders\BooksTableSeeder
Seeded:  Database\Seeders\BooksTableSeeder (131.37ms)
Database seeding completed successfully.
```

**Comment by mgarimelHES** [comment]
Thanks a lot!, Appreciate your help in looking into my issues and resolving them.

regards
