### ISSUE TITLE
Error in installing "fortify"

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#56]
Hi Everyone,
I got the following error while trying to install "fortify" in my p3 project. Can someone please help me figure out the issue?

Thank you,
Yvaral

![error_auth](https://user-images.githubusercontent.com/42287520/163728916-22ee4d12-fc1d-4acf-a504-f0dfd671177e.JPG)

**Comment by susanBuck** [comment]
Hi @YvaGithub - Please include the full error output with questions like these. It looks like a fair amount of the output is cut off in your screenshot.

I suspect you're having the same issue described here: 
https://github.com/susanBuck/e15-spring22/issues/53

To fix, first run `php --version` - if it shows version 8.0.something, run the following command to make sure you have all the necessary extensions:

```bash
> sudo apt-get install php8.0-mbstring php8.0-xml php8.0-dom php8.0-curl php8.0-mysql zip unzip
```

If it shows 8.1.something, run this:

```bash
> sudo apt-get install php8.1-mbstring php8.1-xml php8.1-dom php8.1-curl php8.1-mysql zip unzip
```

**Comment by YvaGithub** [comment]
Thank you Prof Susan. Your tip worked.

**Comment by susanBuck** [comment]
You're welcome! Glad it's resolved.
