### ISSUE TITLE
Error attempting to create Codeception test

### ISSUE THREAD

**Issue by dauger27** [susanBuck/e15-spring22#61]
I was following the Notes for installing and setting up Codeception. I generated the `LoginPageCest.php` file and added the content to the `tryToTest` method. I'm seeing an error where `AcceptanceTester` isn't found. When attempting to run the test, I'm getting the following error:

> Codeception requires "mbstring" extension installed to make tests run          
  If you are not sure, how to install "mbstring", please refer to StackOverflow
> 
> Notice: PHP for Apache/Nginx and CLI can have different php.ini files.         
  Please make sure that your PHP you run from console has "mbstring" enabled.

**Comment by susanBuck** [comment]
Can you update your repo with the latest on Github? 

Also, can you share the full error output that mentions AcceptanceTester not being found?

**Comment by susanBuck** [comment]
RE: the note about missing mbstring extension, see https://github.com/susanBuck/e15-spring22/issues/58 for fix

**Comment by dauger27** [comment]
I am no longer getting the error on the AcceptanceTester. I didn't make any changes after posting this so I'm not certain what ultimately changed. After fixing the mbstring the tests are running successfully.

**Comment by susanBuck** [comment]
Odd about AcceptanceTester resolving itself with no changes, but glad it's working now! 👍
