### ISSUE TITLE
Question: Can Codeception access session data?

### ISSUE THREAD

**Issue by archerdave** [susanBuck/e15-spring22#65]
Does Codeception have any access to the HTTP session data?  For example, when a user logs in, the session gets certain pieces of data.  Checking for this data could be useful in verifying a login.  Perhaps in other cases as well.  I saw that it can do some work with cookies, but I didn't see the session data mentioned.

**Comment by susanBuck** [comment]
You could do something like this...

In _TestController_ add a method we’ll call _meta_ that returns useful meta info (including session data) as json data:

```php
public function meta(Request $request)
{
    return response()->json([
        'user' => $request->user(),
        'cookie' => $request->cookie(),
        'session' => $request->session()->all(),
    ]);
}
```

Then you can access it in tests like so:

```php
$I->amOnPage('/test/meta');
$metaData = json_decode($I->grabPageSource(), true);
```

**Comment by archerdave** [comment]
Thanks, that makes sense.
