### ISSUE TITLE
Help figuring out a solution for the following error

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#68]
![error_auth](https://user-images.githubusercontent.com/42287520/167006760-a6359280-6b3a-485a-a869-962990041845.JPG)
Hello Everyone,
I am looking for some help figuring out how to solve this issue. I have run all the related codes before. Today, as I working on the project, I might have inadvertently deleted a file from the Fortify folder. Now everything seems to be going south.

Anticipated thanks,
Yvaral

**Comment by susanBuck** [comment]
Please share the full output of the error.

**Comment by susanBuck** [comment]
Also, make sure you've read/applied the instructions from this thread: https://github.com/susanBuck/e15-spring22/issues/58

**Comment by archerdave** [comment]
What were trying to run that produced this error?

**Comment by YvaGithub** [comment]
Sorry for the confusion, I thought the command appeared on the screenshot my bad. I was trying to run composer laravel fortify. However, I am closing the issue. It was due to the fact that I commented out some lines in one the pages while I was running a test. After I uncommented the lines, I got a different error but this one is gone.
Thank you for the inputs.
Yvaral
