### ISSUE TITLE
I need some help with setting up VS code Remote Development

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#7]
Good evening, 
As I am trying to configure VS Code for the server, I clicked on "hes-on-DigitalOcean". In the search bar, there is a drop-down list which indicates I should choose the OS of my host while in the bottom the is a message that says: "setting up ssh Host hes-on-DigitalOcean but it has been running for some times (more than 5 minutes). I am not sure if I should choose an OS or let it run in the background hoping it will complete after some time. I am attaching a screenshot for your convenience. Any help will be appreciated.
Thanks,
Yvaral
![remote_dev](https://user-images.githubusercontent.com/42287520/152624970-8138e1bb-3721-4d26-8edc-3c62e6f29267.PNG)

**Comment by susanBuck** [comment]
You should choose Linux.
(Our servers run a LEMP stack, where the L stands for Linux.)

**Comment by YvaGithub** [comment]
I thought of it but I was not sure. It works. Thank you.
