### ISSUE TITLE
Unable to supply default value for form text field

### ISSUE THREAD

**Issue by luannebe** [susanBuck/e15-spring22#70]
Hi,
I would like to supply a default value for a form field. The following works, except that the default value is displayed in the form and saved as "Massachusetts" not "Massachusetts Ave NW." Any thoughts would be much appreciated. 
```
<div class="col-6">
    <label for="street_name" class="form-label">*Street Name</label>
    <input type="text" class="form-control" id="street_name" name="street_name" value={{ old("street_name",  "Massachusetts Ave NW") }}>   
    @include('includes/error-field', ['fieldName' => 'street_name'])      
</div>
```
<img width="824" alt="image" src="https://user-images.githubusercontent.com/2761778/167275207-c38367c8-bc3e-4ef4-933a-238a88d93dd2.png">

**Comment by pllealfunes** [comment]
What if you move your quotation mark from the end of `Massachusetts` to after `nw`? So that it can be `value="Massachusetts Ave NW"`

**Comment by luannebe** [comment]
Hi,
Oh, sorry. I should have explained this better. The upper block is from my code. You have to use the horizontal scroll bar to see all of it.
The lower block is a screen shot of the form field html in the browser, as shown by the Chrome Elements inspector. Somehow, the string up to the first white space gets enclosed in quotes, and the rest is floating to the right.

**Comment by gkorodi** [comment]
Maybe there is just an extra quote missing from the `input` element?!

I tried and this seems to work

`<input type="text" class="form-control" id="street_name" name="street_name" value="{{ old("street_name",  "Massachusetts Ave NW") }}">`

or more closely

` .... value="{{ ..... }}" />`

I think the quotes needed around the whole value that you are printing in the blade template.

**Comment by luannebe** [comment]
Brilliant!!! it works. Thank you @gkorodi and @pllealfunes !
