### ISSUE TITLE
Error_Connecting_To_The_Server

### ISSUE THREAD

**Issue by YvaGithub** [susanBuck/e15-spring22#8]
Hi everyone,
I have been experiencing a connection issue when I am trying to reach my server through the browser. Sometimes it would connect sometimes it won't. I am attaching the error message that I have gotten.
Thank you,
Yvaral
![error_connecting_to_the_server](https://user-images.githubusercontent.com/42287520/152664738-aac66b58-8a6d-4fee-82cc-be4709d99e0b.PNG)

**Comment by susanBuck** [comment]
Hi @YvaGithub - 

Can you look at your DNS settings and see if you have two A Records? **If so, delete any A Records that are not pointing to your DigitalOcean server.**

I think this section addresses the issue you're seeing: 

> If you created a domain via nc.me, you may have an existing A Record pointing to Github pages (a free service they offer you when signing up). You want to either edit or delete this record to set up the A Record to point to your DigitalOcean IP. You should not configure things so you have two A Records, one pointing to the Github pages IP and one pointing to the DigitalOcean IP, as this will cause your domain to sporadically switch between what IP address it's using.

ref: https://hesweb.dev/e15/notes/infrastructure/domains#record-1-main-domain

If that doesn't do the trick, let me know and we can dig deeper!

**Comment by YvaGithub** [comment]
Although they were not mapped to the IP address, I did have few records. It works after I deleted them.
Thank you!
